package SqlServer.Dao;

public class Computer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Computer_software.ComputerID
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    private String computerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Computer_software.software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    private String software;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Computer_software.ComputerID
     *
     * @return the value of Computer_software.ComputerID
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    public String getComputerid() {
        return computerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Computer_software.ComputerID
     *
     * @param computerid the value for Computer_software.ComputerID
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    public void setComputerid(String computerid) {
        this.computerid = computerid == null ? null : computerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Computer_software.software
     *
     * @return the value of Computer_software.software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    public String getSoftware() {
        return software;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Computer_software.software
     *
     * @param software the value for Computer_software.software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    public void setSoftware(String software) {
        this.software = software == null ? null : software.trim();
    }

    @Override
    public String toString() {
        return "Computer{" +
                "computerid='" + computerid + '\'' +
                ", software='" + software + '\'' +
                '}';
    }
}