package SqlServer.mapper;

import SqlServer.Dao.Computer;
import SqlServer.Dao.ComputerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ComputerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    long countByExample(ComputerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    int deleteByExample(ComputerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    int insert(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    int insertSelective(Computer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    List<Computer> selectByExample(ComputerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    int updateByExampleSelective(@Param("record") Computer record, @Param("example") ComputerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Computer_software
     *
     * @mbg.generated Mon Jul 18 16:36:34 CST 2022
     */
    int updateByExample(@Param("record") Computer record, @Param("example") ComputerExample example);
}